exports.seed = async function(knex) {
    await knex("location").insert([
        {city: 'Lagos', country: 'Nigeria'},
        {city: 'Kano', country: 'Nigeria'},
        {city: 'Ibadan', country: 'Nigeria'},
        {city: 'Kaduna', country: 'Nigeria'},
        {city: 'Port Harcourt', country: 'Nigeria'},
        {city: 'Benin', country: 'Nigeria'},
        {city: 'Maiduguri', country: 'Nigeria'},
        {city: 'Zaria', country: 'Nigeria'},
        {city: 'Aba', country: 'Nigeria'},
        {city: 'Ilorin', country: 'Nigeria'},
        {city: 'Jos', country: 'Nigeria'},
        {city: 'Ogbomosho', country: 'Nigeria'},
        {city: 'Ovo', country: 'Nigeria'},
        {city: 'Enugu', country: 'Nigeria'},
        {city: 'Abeokuta', country: 'Nigeria'},
        {city: 'Onitsha', country: 'Nigeria'},
        {city: 'Warri', country: 'Nigeria'},
        {city: 'Sokoto', country: 'Nigeria'},
        {city: 'Okene', country: 'Nigeria'},
        {city: 'Calabar', country: 'Nigeria'},
        {city: 'Oshogbo', country: 'Nigeria'},
        {city: 'Katsina', country: 'Nigeria'},
        {city: 'Akure', country: 'Nigeria'},
        {city: 'Bobo Dioulasso', country: 'Nigeria'},
        {city: 'Ife', country: 'Nigeria'},
        {city: 'Bauchi', country: 'Nigeria'},
        {city: 'Iseyin', country: 'Nigeria'},
        {city: 'Minna', country: 'Nigeria'},
        {city: 'Makurdi', country: 'Nigeria'},
        {city: 'Owo', country: 'Nigeria'},
        {city: 'Ado', country: 'Nigeria'},
        {city: 'Ilesha', country: 'Nigeria'},
        {city: 'Gombe', country: 'Nigeria'},
        {city: 'Umuahia', country: 'Nigeria'},
        {city: 'Ondo', country: 'Nigeria'},
        {city: 'Damaturu', country: 'Nigeria'},
        {city: 'Jimeta', country: 'Nigeria'},
        {city: 'Ikot Ekpene', country: 'Nigeria'},
        {city: 'Gusau', country: 'Nigeria'},
        {city: 'Mubi', country: 'Nigeria'},
        {city: 'Shagumu', country: 'Nigeria'},
        {city: 'Owerri', country: 'Nigeria'},
        {city: 'Ugep', country: 'Nigeria'},
        {city: 'Ijebu Ode', country: 'Nigeria'},
        {city: 'Ise', country: 'Nigeria'},
        {city: 'Gboko', country: 'Nigeria'},
        {city: 'Ilawe', country: 'Nigeria'},
        {city: 'Ikare', country: 'Nigeria'},
        {city: 'Abuja', country: 'Nigeria'},
        {city: 'Okpoko', country: 'Nigeria'},
        {city: 'Awka', country: 'Nigeria'},
        {city: 'Sapele', country: 'Nigeria'},
        {city: 'Ila', country: 'Nigeria'},
        {city: 'Shaki', country: 'Nigeria'},
        {city: 'Ijero', country: 'Nigeria'},
        {city: 'Otukpo', country: 'Nigeria'},
        {city: 'Kishi', country: 'Nigeria'},
        {city: 'Bugama', country: 'Nigeria'},
        {city: 'Funtua', country: 'Nigeria'},
        {city: 'Abakaliki', country: 'Nigeria'},
        {city: 'Gbongan', country: 'Nigeria'},
        {city: 'Lafia', country: 'Nigeria'},
        {city: 'Igboho', country: 'Nigeria'},
        {city: 'Amaigbo', country: 'Nigeria'},
        {city: 'Gashua', country: 'Nigeria'},
        {city: 'Offa', country: 'Nigeria'},
        {city: 'Jalingo', country: 'Nigeria'},
        {city: 'Bama', country: 'Nigeria'},
        {city: 'Uvo', country: 'Nigeria'},
        {city: 'Uromi', country: 'Nigeria'},
        {city: 'Nsukka', country: 'Nigeria'},
        {city: 'Okigwe', country: 'Nigeria'},
        {city: 'Modakeke', country: 'Nigeria'},
        {city: 'Abidjan', country: 'Ivory Coast'},
        {city: 'Bouake', country: 'Ivory Coast'},
        {city: 'Daloa', country: 'Ivory Coast'},
        {city: 'Yamoussoukro', country: 'Ivory Coast'},
        {city: 'Korhogo', country: 'Ivory Coast'},
        {city: 'San Pedro', country: 'Ivory Coast'},
        {city: 'Divo', country: 'Ivory Coast'},
        {city: 'Man', country: 'Ivory Coast'},
        {city: 'Gagnoa', country: 'Ivory Coast'},
        {city: 'Dakar', country: 'Senegal'},
        {city: 'Thies', country: 'Senegal'},
        {city: 'Kaolack', country: 'Senegal'},
        {city: 'Ziguinchor', country: 'Senegal'},
        {city: 'Saint Louis', country: 'Senegal'},
        {city: 'Mbour', country: 'Senegal'},
        {city: 'Diourbel', country: 'Senegal'},
        {city: 'Accra', country: 'Ghana'},
        {city: 'Kumasi', country: 'Ghana'},
        {city: 'Tamale', country: 'Ghana'},
        {city: 'Obuasi', country: 'Ghana'},
        {city: 'Conakry', country: 'Guinea'},
        {city: 'Kankan', country: 'Guinea'},
        {city: 'Bissua', country: 'Guinea-Bissau'},
        {city: 'Douala', country: 'Cameroon'},
        {city: 'Yaounde', country: 'Cameroon'},
        {city: 'Garoua', country: 'Cameroon'},
        {city: 'Maroua', country: 'Cameroon'},
        {city: 'Bafoussan', country: 'Cameroon'},
        {city: 'Ngaoundere', country: 'Cameroon'},
        {city: 'Bamenda', country: 'Cameroon'},
        {city: 'Kaele', country: 'Cameroon'},
        {city: 'Kumba', country: 'Cameroon'},
        {city: 'Freetown', country: 'Sierra Leone'},
        {city: 'Koidu', country: 'Sierra Leone'},
        {city: 'Makeni', country: 'Sierra Leone'},
        {city: 'Ouagadougou', country: 'Burkina Faso'},
        {city: 'Bobo Diolasso', country: 'Burkina Faso'},
        {city: 'Cotonou', country: 'Benin'},
        {city: 'Porto Novo', country: 'Benin'},
        {city: 'Parakou', country: 'Benin'},
        {city: 'Djougou', country: 'Benin'},
        {city: 'Bohicon', country: 'Benin'},
        {city: 'Kandi', country: 'Benin'},
        {city: 'Abomey', country: 'Benin'},
        {city: 'Natitingou', country: 'Benin'},
        {city: 'Lome', country: 'Togo'},
        {city: 'Sokode', country: 'Togo'},
        {city: 'Monrovie', country: 'Liberia'},
        {city: 'Ajdabivah', country: 'Liberia'},
        {city: 'Libreville', country: 'Gabon'},
        {city: 'Port Gentil', country: 'Gabon'},
        {city: 'Serekunda', country: 'Gambia'}
    ])
};
