exports.seed = async function(knex) {
    await knex("location").insert([
        {location: 'Unknown'},
        {location: 'Lagos, Nigeria'},
        {location: 'Kano, Nigeria'},
        {location: 'Ibadan, Nigeria'},
        {location: 'Kaduna, Nigeria'},
        {location: 'Port Harcourt, Nigeria'},
        {location: 'Benin, Nigeria'},
        {location: 'Maiduguri, Nigeria'},
        {location: 'Zaria, Nigeria'},
        {location: 'Aba, Nigeria'},
        {location: 'Ilorin, Nigeria'},
        {location: 'Jos, Nigeria'},
        {location: 'Ogbomosho, Nigeria'},
        {location: 'Ovo, Nigeria'},
        {location: 'Enugu, Nigeria'},
        {location: 'Abeokuta, Nigeria'},
        {location: 'Onitsha, Nigeria'},
        {location: 'Warri, Nigeria'},
        {location: 'Sokoto, Nigeria'},
        {location: 'Okene, Nigeria'},
        {location: 'Calabar, Nigeria'},
        {location: 'Oshogbo, Nigeria'},
        {location: 'Katsina, Nigeria'},
        {location: 'Akure, Nigeria'},
        {location: 'Bobo Dioulasso, Nigeria'},
        {location: 'Ife, Nigeria'},
        {location: 'Bauchi, Nigeria'},
        {location: 'Iseyin, Nigeria'},
        {location: 'Minna, Nigeria'},
        {location: 'Makurdi, Nigeria'},
        {location: 'Owo, Nigeria'},
        {location: 'Ado, Nigeria'},
        {location: 'Ilesha, Nigeria'},
        {location: 'Gombe, Nigeria'},
        {location: 'Umuahia, Nigeria'},
        {location: 'Ondo, Nigeria'},
        {location: 'Damaturu, Nigeria'},
        {location: 'Jimeta, Nigeria'},
        {location: 'Ikot Ekpene, Nigeria'},
        {location: 'Gusau, Nigeria'},
        {location: 'Mubi, Nigeria'},
        {location: 'Shagumu, Nigeria'},
        {location: 'Owerri, Nigeria'},
        {location: 'Ugep, Nigeria'},
        {location: 'Ijebu Ode, Nigeria'},
        {location: 'Ise, Nigeria'},
        {location: 'Gboko, Nigeria'},
        {location: 'Ilawe, Nigeria'},
        {location: 'Ikare, Nigeria'},
        {location: 'Abuja, Nigeria'},
        {location: 'Okpoko, Nigeria'},
        {location: 'Awka, Nigeria'},
        {location: 'Sapele, Nigeria'},
        {location: 'Ila, Nigeria'},
        {location: 'Shaki, Nigeria'},
        {location: 'Ijero, Nigeria'},
        {location: 'Otukpo, Nigeria'},
        {location: 'Kishi, Nigeria'},
        {location: 'Bugama, Nigeria'},
        {location: 'Funtua, Nigeria'},
        {location: 'Abakaliki, Nigeria'},
        {location: 'Gbongan, Nigeria'},
        {location: 'Lafia, Nigeria'},
        {location: 'Igboho, Nigeria'},
        {location: 'Amaigbo, Nigeria'},
        {location: 'Gashua, Nigeria'},
        {location: 'Offa, Nigeria'},
        {location: 'Jalingo, Nigeria'},
        {location: 'Bama, Nigeria'},
        {location: 'Uvo, Nigeria'},
        {location: 'Uromi, Nigeria'},
        {location: 'Nsukka, Nigeria'},
        {location: 'Okigwe, Nigeria'},
        {location: 'Modakeke, Nigeria'},
        {location: 'Abidjan, Ivory Coast'},
        {location: 'Bouake, Ivory Coast'},
        {location: 'Daloa, Ivory Coast'},
        {location: 'Yamoussoukro, Ivory Coast'},
        {location: 'Korhogo, Ivory Coast'},
        {location: 'San Pedro, Ivory Coast'},
        {location: 'Divo, Ivory Coast'},
        {location: 'Man, Ivory Coast'},
        {location: 'Gagnoa, Ivory Coast'},
        {location: 'Dakar, Senegal'},
        {location: 'Thies, Senegal'},
        {location: 'Kaolack, Senegal'},
        {location: 'Ziguinchor, Senegal'},
        {location: 'Saint Louis, Senegal'},
        {location: 'Mbour, Senegal'},
        {location: 'Diourbel, Senegal'},
        {location: 'Accra, Ghana'},
        {location: 'Kumasi, Ghana'},
        {location: 'Tamale, Ghana'},
        {location: 'Obuasi, Ghana'},
        {location: 'Conakry, Guinea'},
        {location: 'Kankan, Guinea'},
        {location: 'Bissua, Guinea-Bissau'},
        {location: 'Douala, Cameroon'},
        {location: 'Yaounde, Cameroon'},
        {location: 'Garoua, Cameroon'},
        {location: 'Maroua, Cameroon'},
        {location: 'Bafoussan, Cameroon'},
        {location: 'Ngaoundere, Cameroon'},
        {location: 'Bamenda, Cameroon'},
        {location: 'Kaele, Cameroon'},
        {location: 'Kumba, Cameroon'},
        {location: 'Freetown, Sierra Leone'},
        {location: 'Koidu, Sierra Leone'},
        {location: 'Makeni, Sierra Leone'},
        {location: 'Ouagadougou, Burkina Faso'},
        {location: 'Bobo Diolasso, Burkina Faso'},
        {location: 'Cotonou, Benin'},
        {location: 'Porto Novo, Benin'},
        {location: 'Parakou, Benin'},
        {location: 'Djougou, Benin'},
        {location: 'Bohicon, Benin'},
        {location: 'Kandi, Benin'},
        {location: 'Abomey, Benin'},
        {location: 'Natitingou, Benin'},
        {location: 'Lome, Togo'},
        {location: 'Sokode, Togo'},
        {location: 'Monrovie, Liberia'},
        {location: 'Ajdabivah, Liberia'},
        {location: 'Libreville, Gabon'},
        {location: 'Port Gentil. Gabon'},
        {location: 'Serekunda, Gambia'}
    ])
};
